"""A thin wrapper around cryptography"""

from cryptography import fernet
from pathlib import Path


def gen_key() -> bytes:
    """Spits out a key generated by fernet"""
    return fernet.Fernet.generate_key()


def _write_file(key: str, source_file: Path, dest_dir: Path):
    enc_data = fernet.Fernet(key).encrypt(source_file.read_bytes())
    enc_file = Path(dest_dir, fernet.Fernet(key).encrypt(source_file.name.encode()).decode())
    enc_file.write_bytes(enc_data)


def encryptor(key: str, source: Path, dest: Path):
    key = key.encode()

    if not dest.exists():
        print(f"Creating directory: {dest}")
        dest.absolute().mkdir()

    if source.is_dir():
        for file_path in source.glob("**/*"):
            _write_file(key, file_path, dest)
    elif source.is_file():
        _write_file(key, source, dest)
    else:
        return f"Source: '{source}' is neither a file or folder, exiting."
